:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\PROCEDURES.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Admin\FrmUserLoginInfo\SP_INSERT_USER_LOGIN_LOG.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Admin\FrmUserLoginInfo\SP_UPDATE_USER_LOGOUT.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Admin\FrmUserLoginInfo\USER_LOGIN_LOGS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmAreas\AREAS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmAreas\SP_GET_AREAS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmAreas\SP_INSERT_AREAS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmCountries\COUNTRY.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmCountries\SP_GET_COUNTRY.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmCountries\SP_INSERT_COUNTRY.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmDepartments\DEPARTMENTS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmDepartments\SP_GET_DEPARTMENTS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmDepartments\SP_INSERT_DEPARTMENTS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmDistricts\DISTRICTS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmDistricts\SP_GET_DISTRICTS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmDistricts\SP_INSERT_DISTRICTS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmMarketingExecutives\MARKETING_EXECUTIVE_ID.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmMarketingExecutives\SP_GET_MARKETING_EXECUTIVE.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmMarketingExecutives\SP_INSERT_MARKETING_EXECUTIVE.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmPlaces\PLACE.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmPlaces\SP_GET_PLACE.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmPlaces\SP_INSERT_PLACE.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmServiceTypes\SERVICE_TYPES.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmServiceTypes\SP_GET_SERVICE_TYPES.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmServiceTypes\SP_INSERT_SERVICE_TYPES.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmSpecilizations\SPECIALIZATION.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmSpecilizations\SP_GET_SPECIALIZATION.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmSpecilizations\SP_INSERT_SPECIALIZATION.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmStates\SP_GET_STATES.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmStates\SP_INSERT_STATES.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmStates\STATES.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmUnits\SP_GET_UNITS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmUnits\SP_INSERT_UNITS.sql 
:r D:\HanuMediSoft\HanuMediSoft\HanuMediSoft\Prodedures\Hms\Op\Masters\FrmUnits\UNITS.sql 
