GO
CREATE OR ALTER PROCEDURE SP_UPDATE_USER_LOGOUT
(
    @LOG_ID      INT,
    @EDIT_USER_ID VARCHAR(50)
)
AS
BEGIN
    UPDATE USER_LOGIN_LOGS
    SET 
        LOGOUT_TIME = GETDATE(),
        EDIT_USER_ID = @EDIT_USER_ID,
        EDIT_DATE = GETDATE()
    WHERE LOG_ID = @LOG_ID;
END
GO
