GO
CREATE TABLE USER_LOGIN_LOGS (
    LOG_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID VARCHAR(50),
    LOGIN_TIME DATETIME DEFAULT GETDATE(),
    LOGOUT_TIME DATETIME NULL,
    IP_ADDRESS NVARCHAR(50),
	IS_ACTIVE_LOGIN NUMERIC,
    BROWSER_INFO NVARCHAR(500),
	ENTRY_USER_NAME    VARCHAR(100),
	ENTRY_USER_ID      VARCHAR(50),
	ENTRY_DATE         DATETIME DEFAULT GETDATE(),
	EDIT_USER_ID       VARCHAR(50),
	EDIT_DATE          DATETIME DEFAULT GETDATE(),
	TERMINAL_ID        VARCHAR(100)
)
GO
 